# Created using wingetcreate 0.4.4.1
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.0.0.schema.json

PackageIdentifier: Cloudflight.DockerInWSL
PackageVersion: 1.0.0.0
PackageLocale: en-US
Publisher: Cloudflight Austria GmbH
PackageName: DockerInWSL
License: Apache2
ShortDescription: Using WSL2 to run a docker on windows (using official dind alpine image)
ManifestType: defaultLocale
ManifestVersion: 1.0.0

