name: Build Choco Package

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Init Build-Env
      run: make init

    - name: Build the Choco Package
      run: make package

    - name: Test install
      run: make install
    
    - name: Test uninstall
      run: make uninstall

    - name: Upload Archive
      uses: actions/upload-artifact@v2
      with:
        name: archive
        path: dockerinwsl*.nupkg
  