name: Build Image

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build the Docker image
      run: make image_7z
    
    - name: Upload Archive (tar)
      uses: actions/upload-artifact@v2
      with:
        name: dockerinwsl-tar
        path: dockerinwsl.tar
    
    - name: Upload Archive (tar.7z)
      uses: actions/upload-artifact@v2
      with:
        name: dockerinwsl-tar-7z
        path: dockerinwsl.tar.7z
  