name: Build Image

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Init Build-Env
      run: make init

    - name: Build the Docker image
      run: make image_7z
    
    - name: Upload Archive
      uses: actions/upload-artifact@v2
      with:
        name: archive
        path: dockerinwsl.tar*
  